image: python

stages:
  - test

before_script:
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source ~/.poetry/env
  - pip install tox

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

python39:
  image: python:3.8
  stage: test
  script: tox -e py38
