repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: git://github.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
-   repo: https://github.com/frankier/seed-isort-config
    rev: 75dc0693fe575ce51f4be91c86447a67aa284d8f
    args: [--exclude=submodules/.*\.py]
    hooks:
    -   id: seed-isort-config
-   repo: git://github.com/timothycrosley/isort 
    rev: master
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
