site_name: SkelShop Documentation
site_description: "Documentation of SkelShop, a toolkit for offline skeleton and face analysis of talking heads videos"
repo_url: "https://github.com/frankier/skelshop"
repo_name: "frankier/skelshop"

nav:
  - Getting started: index.md
  - 'User guide (for users of the command line tools)':
    - Pipelines overview: pipelines-overview.md
    - 'Meet the...':
      - Pose estimators: pose-estimators.md
      - Shot segmentors: shot-segmentors.md
      - Within-shot pose trackers: pose-trackers.md
      - 'Face chip detectors/croppers': face-extractors.md
      - Face embedders: face-embedders.md
    - Usage examples: usage-examples.md
    - Benchmarks: benchmark.md
    - HPC extraction with Snakemake: snakemake.md
  - 'Developer guide (for users of the library & contributors)': 
    - Pipeline internals: pipeline-internals.md
    - Tracking: tracking.md
    - Formats: formats.md
    - Reading and writing the formats from your own code: io.md
    - Contributing: development.md
  - Reference:
    - CLI reference: cli.md
  - 'Issues': https://github.com/frankier/skelshop/issues
  - 'Discussion & Questions': https://github.com/frankier/skelshop/discussions

theme:
  name: "material"

markdown_extensions:
  - admonition
  - mkdocs-click
  - footnotes
  - markdown_inline_graphviz

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: true
      watch:
        - skelshop
